### ISSUE TITLE
Development Checklist

### ISSUE THREAD

**Issue by nasrulhazim** [nasrulhazim/arch#1]
## Features

- [ ] Multilingual
- [ ] General Settings

### Artisan Commands

- [ ] `arch:field` - `app/Arch/Field` -> create fields based on given model.
- [ ] `arch:manage` - `app/Arch/Manage` -> CRUD the given field 
- [ ] `arch:action` - `app/Arch/Action` -> Action for given field 
- [ ] `arch:deck` - `app/Arch/Deck` -> Chart for given field 
- [ ] `arch:menu` - `storage/arch/menus` -> Store menu in json format
- [ ] `arch:config` - `config/arch.php` -> Override any arch config and store in database.
- [ ] `arch:route` - `routes/arch/*.php` -> arch routes, if any.

### User 

- [x] Profile 
- [x] Upload Avatar
- [ ] Security
	- [x] Password
	- [ ] 2FA
	- [ ] Secret Question & Answer
- [ ] Activities (previously known as Log)
- [ ] Media

### Manage

- [ ] Locales
	- [ ] Enable / Disable Locales
- [x] OAuth
- [ ] User
	- [ ] Account Expiry
	- [ ] Password Expiry
	- [ ] Reset Password
- [ ] Role & Permission
	- [ ] Consider Lock Mechanism
	- [x] Access Control Level
- [ ] Media 
- [x] Resource Management
	- [x] Listing
	- [x] Searching
	- [x] Filtering
	- [x] Actions

## Setup 

- [x] PHP CS Fixer
- [x] PHPUnit Test 
	- [x] API Endpoint
	- [x] Custom Asserts
- [x] .htaccess
- [x] Locales
- [ ] Packages
	- [x] Appstract: Laravel Blade Directives
	- [x] Barryvdh: Debugbar
	- [x] Dave James Miller: Laravel Breadcrumbs
	- [x] Cleanieque Coders: Blade Plus Plus
	- [x] Cleanieque Coders: Blueprint Macro
	- [x] Cleanieque Coders: Profile
	- [x] Cleanieque Coders: Laravel Helper
	- [x] Cleanieque Coders: Laravel Observers
	- [x] Laravel: Dusk
	- [x] Laravel: Horizon
	- [ ] Laravel: Lumen
	- [ ] Laravel: Socialite
	- [x] Laravel: Telescope
	- [x] Laravel: Passport
	- [x] Owen It: Laravel Auditing
	- [x] Predis: Predis
	- [x] Renatomarinho: Laravel Page Speed
	- [x] Spatie: Image Optimizer
	- [x] Spatie: Laravel Permission
	- [x] Spatie: Laravel Media Libary
	- [x] Spatie: Laravel Response Cache
	- [x] Tighten Co.: Ziggy
